# IoT Claim Certificate and Policy used for Fleet Provisioning
# Devices are pre-flashed with these credentials at the factory.
# The claim cert is single-use: once provisioned, device stores a permanent cert.

# ── Claim Certificate (auto-generated by AWS IoT) ────────────────────────────
resource "aws_iot_certificate" "claim" {
  active = true
}

# ── Claim Policy: minimal permissions for Fleet Provisioning only ─────────────
resource "aws_iot_policy" "claim" {
  name = "${var.project_name}-ClaimPolicy"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid      = "AllowClaimConnect"
        Effect   = "Allow"
        Action   = "iot:Connect"
        Resource = "arn:aws:iot:${var.aws_region}:*:client/claim-*"
      },
      {
        Sid    = "AllowProvisioningPublish"
        Effect = "Allow"
        Action = "iot:Publish"
        Resource = [
          "arn:aws:iot:${var.aws_region}:*:topic/$aws/certificates/create/json",
          "arn:aws:iot:${var.aws_region}:*:topic/$aws/provisioning-templates/${var.project_name}-SwitchTemplate/provision/json",
          "arn:aws:iot:${var.aws_region}:*:topic/$aws/provisioning-templates/${var.project_name}-SensorTemplate/provision/json"
        ]
      },
      {
        Sid    = "AllowProvisioningSubscribe"
        Effect = "Allow"
        Action = ["iot:Subscribe", "iot:Receive"]
        Resource = [
          "arn:aws:iot:${var.aws_region}:*:topicfilter/$aws/certificates/create/json/accepted",
          "arn:aws:iot:${var.aws_region}:*:topicfilter/$aws/certificates/create/json/rejected",
          "arn:aws:iot:${var.aws_region}:*:topicfilter/$aws/provisioning-templates/${var.project_name}-SwitchTemplate/provision/json/accepted",
          "arn:aws:iot:${var.aws_region}:*:topicfilter/$aws/provisioning-templates/${var.project_name}-SwitchTemplate/provision/json/rejected",
          "arn:aws:iot:${var.aws_region}:*:topicfilter/$aws/provisioning-templates/${var.project_name}-SensorTemplate/provision/json/accepted",
          "arn:aws:iot:${var.aws_region}:*:topicfilter/$aws/provisioning-templates/${var.project_name}-SensorTemplate/provision/json/rejected"
        ]
      }
    ]
  })
}

resource "aws_iot_policy_attachment" "claim_cert" {
  policy = aws_iot_policy.claim.name
  target = aws_iot_certificate.claim.arn
}
